WagnerGroup/pyqmc

- mc.py
[metropolis_vs_forcebias_acceptance.pdf](https://github.com/WagnerGroup/pyqmc/files/3183216/metropolis_vs_forcebias_acceptance.pdf)
Acceptance rate is lower for small timesteps, higher for large timesteps.
[energy_trace_fb_vs_metropolis.pdf](https://github.com/WagnerGroup/pyqmc/files/3183249/energy_trace_fb_vs_metropolis.pdf)
The Force-Bias monte carlo step converges faster than metropolis.
[extreme_energy_trace.pdf]
(https://github.com/WagnerGroup/pyqmc/files/3183258/extreme_energy_trace.pdf)
Force-bias is also more robust than metropolis.
> Implemented Force-Bias Monte Carlo Step

- pyqmc/mc.py
I think there is a minor error in limdrift. If the cutoff is not one the drift isn't scaled.
> Fix limdrift for cases when cutoff != 1

- pyqmc/jastrowspin.py
Store partial sums for current configurations so that they don't get re-evaluated each time testvalue() is called. Should speed up ecp evaluation by about a factor of 2.
Create functions _a_update(), _b_update() for compute the partial sums, remove functions _get_deltaa(), _get_deltab() since the former functions do most of their work.
> Store partial sums in jastrow

- pyqmc/coord.py
- pyqmc/jastrowspin.py
- pyqmc/slateruhf.py
- pyqmc/testwf.py
Condensed some of the jastrow code. Still passes all the tests. Maybe reduced number of numpy calls, made the code shorter and easier to read. Ran black, caused minor changes to coord.py, slateruhf.py, testwf.py.
> Jastrow cleanup

- pyqmc/reblock.py
- tests/test_dmc.py
- tests/test_multislater.py
- tests/test_periodic.py
- tests/test_vmc.py
Addressing issue #94 
Implemented reblocking in our own code and checked against pyblock. (The reblock test still passes as well.) optimally_reblock() has the same interface as before; added function reblock(df, n) to reblock n times.
In all tests that run VMC and DMC, I reblocked the data twice before computing errors. Not rigorous, but I think the error estimates will be better now. Can change again if we want to improve.
Also changed test configurations in test_multislater.py to initial_guess instead of np.random.random
> Reblock and more reliable tests

- pyqmc/func3d.py
- pyqmc/jastrowspin.py
- tests/test_derivatives.py
- tests/test_vmc.py
This pull request includes several changes to condense and speed up the jastrow code (mostly in the basis functions). The speedup seems to be up to 5%, mostly from passing distances r to all func3d functions.
- Pass distances r as input to every func3d function to avoid redundant norm calculations
- Added function gradient_laplacian to all basis functions to combine gradient and laplacian computations
- Added test for basis function pgradient
- Fixed bug in CutoffCuspFunction.pgradient for parameter rcut
- Mask inputs by (r <= rcut) for all functions in PolyPadeFunction and CutoffCuspFunction
- Small speed improvements by rearranging arithmetic
- Condensed code to make shorter and more readable
> Jastrow speed improvements and code organization

- pyqmc/multislater.py
Fixed a bug, if statement passed when mc had only 2 orbitals instead of intended purpose of only passing when mc has different orbitals for different spin.
> bugfix in multislater

- pyqmc/slateruhf.py
PySCFSlaterUHF._aovals is set in recompute() and used in pgradient(), but not updated in updateinternals. The derivative test uses recompute() for the numerical derivative, so this doesn't come up in the test.
This change updates _aovals in updateinternals, but doesn't change the test.
> Update PySCFSlaterUHF._aovals in updateinternals()

- pyqmc/dasktools.py
Simple change: the later epochs have their first step shifted by the number of steps in the previous epochs rather than by the number of previous epochs. Otherwise the steps are not labeled correctly when there is more than one epoch.
> Bug fix for dask VMC with multiple epochs.

- pyqmc/__init__.py
Ion cusps can be added for the `default_jastrow` by setting `ion_cusp=True`. Defaults to off.
Here's a graphical check. This is the result of running `line_minimization` with `ion_cusp=True` and freezing the ion and electron cusps. The system is H-He with 2 electrons, one at the origin and one along the z axis. 
[check_elocal.pdf](https://github.com/WagnerGroup/pyqmc/files/3848713/check_elocal.pdf)
> Added an option for ion cusps.

- pyqmc/tbdm.py
Doc strings and comments in tbdm.py had a mistake in the tbdm's index convention (for both pyscf and qwalk). Only fixed these. The tbdm implementation (using pyscf's convention) was correct though.
> Fixed tbdm.py doc strings and comments

- doc/source/ewald.rst
- doc/source/index.rst
- pyqmc/__init__.py
- pyqmc/accumulators.py
- pyqmc/ewald.py
- tests/test_ewald.py
Added documentation to ewald.py, including all the formulas used. Made a few changes to print statements, and enabled ewald kwargs (gmax and nlatvec) to be passed through gradient_generator().
> Ewald documentation

- tests/test_dmc.py
Changed reblocking in test_dmc to use 20 blocks instead of optimally_reblocked, which sometimes didn't find an optimal number of reblocks. Increased number of steps to 4000 plus 200 warmup.
> Dmc test reblocking

- pyqmc/mc.py
When no electrons are "left over", the core assignments were not made (the electrons were distributed around the origin instead of around atom centers. This pull request fixes issue #137, which was caused by very poor initial guesses for large systems.
> make initial_guess assign core electrons even when none are left over

- pyqmc/coord.py
- pyqmc/dmc.py
- pyqmc/linemin.py
- pyqmc/mc.py
OpenConfigs and PeriodicConfigs have three new functions that take in an h5py.File object:
initialize_hdf(hdf): call hdf.create_dataset() for each attribute (configs, wrap, etc)
to_hdf(hdf): write the current attributes to hdf
load_hdf(hdf): overwrite attributes with values from hdf
vmc, dmc, and linemin now load and save configs using this interface.
> Create hdf interface in Configs objects

- pyqmc/__init__.py
- pyqmc/eval_ecp.py
- pyqmc/jastrowspin.py
- pyqmc/multiplywf.py
- pyqmc/multislater.py
- pyqmc/slaterpbc.py
- pyqmc/slateruhf.py
This fixes an error in the nonlocal part of the ecp calculation for pbcs, where get_r_ea_i didn't use a pbc distance calculator. 
This PR also includes a check for whether each atom atom is in the ecp dict, so ecps can be used for a subset of atomic species.
> fix pbc error in eval_ecp.get_r_ea_i and check for atoms with ecps

- pyqmc/manybody_jastrow.py
- pyqmc/multislater.py
- pyqmc/multislaterpbc.py
- pyqmc/slaterpbc.py
- pyqmc/testwf.py
- tests/unit/test_derivatives.py
Implemented MultiSlaterPBC and test. Also includes parameter gradients and passes test. 
For parameter gradients, I changed the parameters from list of kpoints to an array of MO coefficients concatenated over kpoints (for both SlaterPBC and MultiSlaterPBC) just like is done to construct determinants. Using a numpy array makes pgradient compatible with our other functions.
Added function evaluate_mos to SlaterPBC and MultiSlaterPBC to simplify the code in testvalue, gradient, etc.
> Periodic multislater and periodic parameter gradients

- tests/integration/test_obdm.py
addressing issue #161 by using a 4-electron supercell instead of 8 electrons.
> use smaller system to speed up test_obdm

- pyqmc/accumulators.py
- pyqmc/multislaterpbc.py
- pyqmc/slater.py
short fix: twist was just added to kpoints and compared against mf.kpts; if it was a reciprocal lattice vector away, it would result in an error. This PR fixes the error by checking if the differences are zero modulo reciprocal lattice vectors.
> fix twist bug; kpoints are periodic

- pyqmc/slater.py
in PySCFSlater for pbc, iscomplex was being defined before the parameters were set, so it ignored them. now it's defined after the parameters are set.
> check complex after defining the parameters

- pyqmc/reblock.py
moved functions around so that the ones most likely to be used are at the top
added a couple docstrings
moved _reblock() inside of reblock() to avoid confusion
looks like the other functions (i.e. optimally_reblocked and its helpers) still work as intended.
> Reorganize reblock.py

- pyqmc/accumulators.py
- pyqmc/obdm.py
- pyqmc/tbdm.py
- tests/unit/test_accumulators.py
Addressing issue #175 Accumulator functions
Energy, PGrad, OBDM, TBDM, Sq now all have the functions:
keys(): returns a set
shapes(): returns a dict whose keys are keys() and values are shapes. scalars have shape ()
I changed the definition of avg() in obdm and tbdm to the one-line version, since it does the same thing.
In tbdm I moved "ijkl" from avg() to a new function information(). I'm still not sure why we don't just use tbdm_acc._ijkl to get the array.
> add functions keys() and shapes() to accumulators

- pyqmc/__init__.py
apparently mol.atom_charges() references a mutable attribute of mol. default_jastrow is changed to use a copy of mol.atom_charges() to leave the mol object intact.
> use a *copy* of mol.atom_charges() in default_jastrow

- pyqmc/accumulators.py
it was making the regularization function complex, and broke the pgrad averaging. it seems better behaved now.
> make the distance in _node_regr real-valued

- examples/excited_state.py
The excited state example code still had imports from the old pyqmc.dasktools. I fixed that. Also, first pull request from me. :)
> Removed imports from dasktools

- pyqmc/accumulators.py
- pyqmc/slater.py
- tests/integration/test_complex_linemin.py
Parameter derivatives (e.g. dp<H>) for complex p are separated into derivatives w.r.t. the real and imaginary parts. Implemented in LinearTransform by appending the imaginary parts to the parameter list (of real parts).
The test runs a few iterations of linemin on a periodic system with complex MO coeffs to make sure it runs without error. I checked a longer run of this test manually to ensure that the optimization looks reasonable, but don't have an idea for an "assert test" yet.
Slater init_pbc now checks shape of mf instead of type (RHF/UHF), so that recover_pyscf works for KUHF objects.
> separate complex parameters in LinearTransform

- pyqmc/optimize_ortho.py
- tests/unit/test_overlap_derivative.py
The evaluation of S_derivative was fixed (square root of normalization and factor of 0.5).
A test for S_derivative and N_derivative was added.
optimize_orthogonal.evaluate() no longer does the sampling; it takes the results of the sampling as an input instead.
optimize_orthogonal.sample_overlap_worker() records acceptance ratio
> Fix optimize_orthogonal

- pyqmc/optimize_ortho.py
the last pull request was missing a couple things.
The restart check requires import os
The second call to evaluate needed to be changed to the new input
> fix second evaluate() call and import os

- doc/source/methods.rst
- doc/source/wavefunction.rst
- pyqmc/linemin.py
- pyqmc/optimize_ortho.py
The energy derivatives are made real, as they are in linemin.
The phase of the overlap is not important - the total_derivative is now defined only using the derivative of the magnitude of the overlaps.
Making these derivatives real improves the convergence of the complex-parameter molecule.
> Fix complex derivatives in orthogonal optimization

- pyqmc/multislater.py
- pyqmc/multislaterpbc.py
- pyqmc/slater.py
- pyqmc/testwf.py
The mask wasn't used for updating aovals in the slater objects. This PR changes updateinternals in the Slater objects to update aovals using the mask, and only evaluate orbitals where updates are needed. It also adds a test in pyqmc.testwf.test_updateinternals() that the previous version fails.
> update aovals with mask for computing pgradient

- pyqmc/multislater.py
- pyqmc/multislaterpbc.py
fixes issue #236 
Computes determinant values as a ratio with a reference determinant instead of adding together "raw" determinant values.
> use reference determinant in multislater value()

- pyqmc/accumulators.py
- pyqmc/ewald.py
ProcessPoolExecutor failed with pbcs because of defining `compute_energy` as a nested function in EnergyAccumulator. This PR defines the function in the Ewald class, so that is has access to the ewald object's energy function and the same inputs as the original energy function.
> fix bug parallelizing pbcs

- pyqmc/ewald.py
- reciprocal electron (ee and ei) are separated out from ewald_electron
- the implementation that stores separate electrons contributions was replaced by a function that does not compute them separately (the separated function is still in the class but not used)
- dot + transpose is replaced with einsum
- complex exp is replaced with sin and cos
- energy_separated now raises a NotImplementedError because we don't compute the separated values
> speed up ewald reciprocal electron

- pyqmc/func3d.py
- pyqmc/testwf.py
- tests/integration/test_multislater.py
- tests/unit/test_derivatives.py
Addresses issue #259 to make testwf output formats more consistent, and remove the quantities we are not using. Functions test_wf_gradient, test_wf_laplacian, and test_wf_pgradient (and the corresponding func3d functions) return just the max absolute error. Functions test_updateinternals, test_wf_gradient_laplacian, and test_func3d_gradient_laplacian return a dict of max abs error for the different quantities.
> clean up testwf and func3d test output formats

- pyqmc/coord.py
no need to create a new distance object when calling configs.electron(e).
> return *Electron object from *Configs.electron() function

- pyqmc/distance.py
check if lattice vectors are diagonal -> no need for einsums to convert to fractional coordinates and back.
> add diagonal_dist_i for faster distance calculation

- pyqmc/dmc.py
dmc_propagate_parallel wasn't fixed to distribute weights unevenly across cores.
Fixes:
Uses np.array_split instead of np.split for non-even division of weights array
"weight" return value is weighted by confweight before applied to accumulators
`confweight_avg` is removed
The reweighting formula is explained in math in the docstring to avoid future confusion.
> fix dmc parallelization when ncore doesn't divide nconfigs

- pyqmc/loadcupy.py
if cupy is available but no GPU is available, a ModuleNotFoundError will not be raised, but a RuntimeError will be raised when cupy attempts to allocate an array. To catch this more cleanly than the original implementation, this PR uses the cupy.cuda.is_available() function and raises a custom-defined NoGPUFoundError.
> fix loadcupy

- pyqmc/ewald.py
- pyqmc/linemin.py
- pyqmc/loadcupy.py
- pyqmc/mc.py
- pyqmc/orbitals.py
- pyqmc/pbc_eval_gto.py
- pyqmc/slater.py
some small changes for small speed improvements:
- use GPU for Ewald reciprocal_space_electron 
- replace gradient() with gradient_value() in vmc (maybe we can drop the gradient() function)
- mask determinant lists before expanding det_map instead of after
cleanup: remove get_array_module from linemin, since all wf parameters are cupy
> Speed improvements with GPU

- pyqmc/ewald.py
- tests/unit/test_ewald.py
ewald was giving different e-i energy for different ion positions, due to a flipped minus sign. This has been fixed. 
A test was added to check that the ee, ei, ii terms are the same when an atom is shifted in the cell.
> fix ewald sign error and add new test

- pyqmc/determinant_tools.py
- pyqmc/ewald.py
- pyqmc/jastrowspin.py
- pyqmc/obdm.py
- pyqmc/orbitals.py
- pyqmc/recipes.py
- pyqmc/slater.py
- pyqmc/tbdm.py
- pyqmc/wftools.py
- tests/conftest.py
- tests/unit/test_constraints.py
- tests/unit/test_wf_derivatives.py
We now allow for a determinants keyword in Slater, which allows the user to construct wave functions by hand. This works for both open and periodic boundary conditions. While testing this, I found a few small bugs in OBDM and TBDM that were fixed.
> Manual specification of determinants

- pyqmc/dmc.py
- pyqmc/obdm.py
- pyqmc/orbitals.py
- pyqmc/slater.py
- pyqmc/tbdm.py
DMC did not work with TBDM as written because `__call__` should return only quantities _per_ walker, and it was returning acceptances that were not per walker. Also fix a performance bug where warmup was done in `__init__` which caused serious lags when running in parallel.
> Fix tbdm dmc

- pyqmc/linemin.py
- pyqmc/optimize_ortho.py
in linemin:
1. use kwarg `warmup_options` for warmup parameters (like in optimize_orthogonal) instead of using vmcoptions. Default `warmup_options` is to warm up for 10 steps (instead of 100) with the same tstep as vmcoptions.
2. remove kwarg `warmup` from linemin since it isn't being used.
in optimize_orthogonal: 
1. change default `warmup_options` to warm up for 10 steps (instead of 100) and use same tstep as `sample_options`
2. change default `warmup` (steps to throw away each iteration) from 5 to 1.
> shorten warmup time before optimization

- examples/he_recipe.py
- examples/he_recipe_mpi.py
- examples/tutorial.ipynb
- pyqmc/recipes.py
Following commit e59ae4c415e35c6d039ea9e28387f7c65bde780d where recipes were modified (kwargs passed instead of dictionary), the He examples and tutorial needed modification.
Also fixed read_mc_output() in recipes.py which was using the unknown method pyqmc.reblock.avg_reblock().
> Made some small fixes on examples using recipes

- examples/h2_restarts_example.py
- pyqmc/dmc.py
- pyqmc/mc.py
- pyqmc/recipes.py
E.g. restart vmc from `vmc1.hdf` and continue recording in `vmc2.hdf`.
In the recipes, I changed all `start_from` keywords to `starting_wf` to avoid confusion with the previous version. vmc() and rundmc() take kwarg `restart_from`, which is the filename of the run to continue from.
I also added an example to demonstrate the new option.
> Enable restarts from different files

- pyqmc/accumulators.py
- pyqmc/optimize_ortho.py
in _node_regr we have the line d2 += np.sum(np.abs(wf.gradient(e, configs.electron(e))) ** 2, axis=0). this is the same quantity grad2 that is computed by energy.kinetic after the recent DMC upgrade. 
This change reuses grad2 instead of computing all the gradients again.
optimize_ortho.collect_overlap_data calls pgrad._node_regr directly, as well as callign pgrad.avg. grad2 is being computed twice here, but I haven't figured out how to reuse it, so it's recomputed in collect_overlap_data for now.
> use grad2 in node_regr

- pyqmc/linemin.py
- pyqmc/optimize_ortho.py
linemin was using a fit procedure that sometimes made poor moves. This is improved by two changes:
1) include the current parameter point in the list of correlated samples
2) if the proposed move is higher than the minimum test point, use the minimum test point instead.
> use new stable_fit3 in linemin

- pyqmc/ewald.py
cupy.einsum can only act on cupy arrays; it doesn't automatically convert from numpy, so that has to be done explicitly.
> move arrays to gpus for calculating ewald gpoints

- .github/workflows/python-package.yml
- doc/source/snippets.md
- pyqmc/determinant_tools.py
- pyqmc/mc.py
- pyqmc/orbitals.py
- pyqmc/pbc.py
- pyqmc/slater.py
- pyqmc/testwf.py
- tests/conftest.py
- tests/integration/test_obdm.py
- tests/integration/test_periodic.py
- tests/integration/test_twist.py
- tests/unit/test_wf_derivatives.py
I noticed that aovals were sometimes zeros when using pyscf 2.0. I think the culprit was the 'optimized' computation for PBCs. If we are going to make that optimization, we need to make sure that it gets put into pyscf, so it doesn't go out of date.
Also made sure that we are treating things correctly when there are zeros in the wave function, for slater.
> Updates for pyscf 2.01

- pyqmc/twists.py
- tests/unit/test_twists.py
Added pyqmc/twists.py which contains a function that returns all valid twists for a QMC calculation given a primitive cell, mf object and a supercell transformation matrix. Added tests/unit/test_twists.py for testing.
> Added an available_twists function

- pyqmc/obdm.py
- pyqmc/tbdm.py
Mostly add documentation for RDMs. In TBDM, conjugate phi_j(r') and phi_l(r'), which seems to be consistent with the other formulas.
> Tbdm complex

- pyqmc/accumulators.py
- pyqmc/slater.py
Joao pointed out a couple errors with arrays on CPU vs GPU: Slater inverse matrices and det_coeff need to be stored on GPU, and frozen_parms in LinearTransform is expected to be on CPU.
> Gpu bugfix

- pyqmc/linemin.py
old warmup default was nblocks=3, nsteps_per_block=10
changed to: nblocks=1, nsteps_per_block=100
Better default of 100 steps instead of just 30, and can do all in one block for efficiency since we don't collect any data.
> increase optimization warmup default to 100 steps

- pyqmc/orbitals.py
This should resolve issue #292 , that varying number of electrons per kpt raised an error. The test case in #292 no longer errors.
> fix different nelec per kpt -- concatenate flattened occup

- pyqmc/coord.py
Problem: configs was resized when a new shape was saved, but wrap was not resized for wrap shape (configs was resized again)
Fix: resize wrap for wrap shape
> fix bug saving new pbc configs shape

- examples/excited_state.py
- examples/excited_state_h2.py
- pyqmc/optimize_ortho.py
- pyqmc/wftools.py
Was not working because the imports were out of date, and h5py requires specifying writing modes.
The imports are now updated, and h5py call uses append mode.
required two other fixes to the main code:
1. default npartitions in optimize_orthogonal
2. include def_coeff in to_opt even if not optimizing
> update excited_state.py example

- pyqmc/coord.py
- pyqmc/determinant_tools.py
- pyqmc/pyscftools.py
- pyqmc/slater.py
-Checked for attribute "len" instead of "__len__"
-Create UCASCI when reading UHF
-Fix determinant list format
-Correctly handle when ncore is a 2-tuple instead of int
> Some bugfixes with CASCI recipe

- pyqmc/accumulators.py
- pyqmc/ewald.py
- tests/unit/test_accumulators.py
- tests/unit/test_ewald.py
- tests/unit/test_sq.py
This PR adds spinSq to the existing SqAccumulator. Since most of the calculation is the same for Sq and spin-Sq, and they are pretty cheap anyway, it seemed simpler to compute them together rather than make a new accumulator that is almost the same. 
Both Sq and spinSq pass the test that at large q they approach 1.
A notable change is that the constructor requires an extra argument, the electron numbers (nup, ndown).
> add spinSq to SqAccumulator

- pyqmc/addwf.py
- pyqmc/dmc.py
- pyqmc/eval_ecp.py
- pyqmc/j3.py
- pyqmc/jastrowspin.py
- pyqmc/multiplywf.py
- pyqmc/obdm.py
- pyqmc/optimize_ortho.py
- pyqmc/orbitals.py
- pyqmc/slater.py
- pyqmc/tbdm.py
- pyqmc/testwf.py
- pyqmc/three_body_jastrow.py
- tests/conftest.py
In several places, we use statements like `dtype=complex if wf.iscomplex else float`.
These are replaced by `dtype=wf.dtype`.
Orbitals have ao_dtype as well as mo_dtype, since AOs may be real even if MO coefficients are complex.
> use dtype attribute instead of iscomplex where appropriate

- pyqmc/accumulators.py
- tests/unit/test_accumulators.py
Allows us to initialize a symmetry accumulator for vmc or dmc. Tells us how the many-body wave function transforms under symmetry operations of a point group.
> Added SymmetryAccumulator class to accumulators.py

- pyqmc/optimize_ortho.py
I mistakenly lost my original branch where I did this last year. Here's a fresh PR for errors in excited state optimization.
> Added errors for energy, overlaps, and norm in optimize_ortho.py

- pyqmc/linemin.py
- pyqmc/optimize_excited_states.py
- pyqmc/optimize_ortho.py
- pyqmc/three_body_jastrow.py
Correlated sampling line_cost has much smaller fluctuations when using the same random numbers to evaluate ECPs at each parameter sample.
This PR saves the random state before looping over parameter samples, then sets the random state to the saved state each iteration.
Change implemented in linemin.py, optimize_ortho.py, optimize_excited_states.py.
> Correlated sampling for ECPs

- pyqmc/geminaljastrow.py
- pyqmc/obdm.py
- pyqmc/orbitals.py
- pyqmc/pyscftools.py
- pyqmc/slater.py
- pyqmc/tbdm.py
- tests/integration/test_twist.py
- tests/unit/test_wf_derivatives.py
The precision for GTO evaluation can be now specified as a `slater_kws` (`eval_gto_precision`). It is used for determining the rcut for a periodic system. The default value of precision is 0.01.
> Set precision for GTO evaulation as kwarg for a number of classes, determined on a default value, modified some tests

- pyqmc/distance.py
instead of checking each pair of lattice vectors manually (and separating 2d and 3d cases), dot the lattice vectors with themselves and check that the matrix is diagonal.
> cleaner way to check orthogonal lattice vectors

- pyqmc/ewald.py
- pyqmc/orbitals.py
Add `optimize="greedy"` to einsum calls in orbitals.mos and ewald.reciprocal_space_electron.
This seems to speed up the calls noticeably, the mos() having bigger impact.
> set optimize='greedy'

- pyqmc/eval_ecp.py
Fix the following key error
```Traceback (most recent call last):
File "/projects/wagner/cychow2/.conda/envs/cco-new/lib/python3.11/concurrent/futures/process.py", line 256, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/projects/wagner/cychow2/.conda/envs/cco-new/lib/python3.11/site-packages/pyqmc/dmc.py", line 171, in dmc_propagate
newepos, mask, probability, ecp_totweight = propose_tmoves(
^^^^^^^^^^^^^^^
File "/projects/wagner/cychow2/.conda/envs/cco-new/lib/python3.11/site-packages/pyqmc/dmc.py", line 83, in propose_tmoves
moves = energy_accumulator.nonlocal_tmoves(configs, wf, e, tstep)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fix a key error in compute_tmoves() in eval_ecp.py

- pyqmc/testwf.py
- pyqmc/three_body_jastrow.py
- tests/conftest.py
- tests/unit/test_aux_testvalue.py
Addresses issue #432 , three-body jastrow testvalue did not work for ECPs, now fixed.
Additionally, added a test that catches that error.
> add new test for testvalue with aux coordinates

- pyqmc/testwf.py
`error[max(error)]` was intended to return the maximum error in the dictionary `error`, however, `max(error)` returns the maximum of the keys themselves, not the key of the maximum value. So this is changed to `max(error.values())`.
> fix pgradient test error check

- pyqmc/wftools.py
The previous implementation fix the maximum determinant parameter when setting up `to_opt["det_coeff"]` to fix the normalization of the wf, but when the leading determinant coefficient is negative, the code doesn't work as intended.
So instead of fixing the maximum parameter, I modified the code to fix the maximum absolute parameter.
> Fix the max absolute instead of max determinant parameter when creating to_opt

- pyqmc/pyscftools.py
Pyscf seems to have a bug if you use to_uhf()  and then convert_to_khf. It does work the other way around.
> Reverse order of convert_to_khf and to_uhf()

- pyqmc/linemin.py
Fixed the bug where an iteration is skipped when restarting optimization, caused by the extra +1 in setting the `iteration_offset`.
> Fixed skipped iteration when restarting line minimization

- pyqmc/pbc/supercell.py
- tests/unit/test_supercell_charge.py
When generating wave functions for charged PBC systems, the charge attribute was not transferred to the supercell object. This resulted in incorrect total electron number for the supercell. I added a line to patch that.
> Transfer cell.charge to supercell

- pyqmc/wf/jax/slater.py
Now JAX Slater should read `mo_coeff` from `mc` objects when available.
> Fix JAX Slater not reading mo_coeff from mc objects
