- func3d.py
- testwf.py
Implemented tests for func3d gradient and laplacian functions.
> func3d tests 

- test_most.py
> Added testing for UHF

- jastrow.py
Change in Jastrow2B for it to be able to take user-defined basis functions
> User-defined basis functions to Jastrow2B

- slater.py
add together components before doing matrix products
> faster slater.laplacian()

- energy.py
- eval_ecp.py
- mc.py
The ECP evaluation still needs more tests. Currently it only supports naip=6, so it might not work if you have higher than p channel in your ecp.
> ECP evaluation 

- jastrow.py
Added the a values for electron-ion jastrow term.
testwf.py throws an error in the pgradient test because the a values are of higher dimension than b values. When we comment out the a value parameter derivative, the test runs just fine.
> Updated Jastrow for 1 and 2 body terms

- optvariance.py
Variance optimization (with numerical derivatives). Not using accumulators so far. Optimization only tested for the Jastrow basis functions coefficients. Written such that it is straightforward to do stochastic reconfiguration.
> Added variance optimization (no gradient).

- eval_ecp.py
- test_most.py
Now it should pass the build test
> The ECP test

- obdm.py
I'm very sure it's working for MO basis orbitals, still checking for other choices of basis.
> Major bug fixes for OBDM

- accumulators.py
> Fix PGrad to use einsum and maintain shape of (nconfigs,nparams)

- pyqmc/jastrowspin.py
- tests/test_dmc.py
Added new index on 'acoeff' of 'jastrowspin.py' so parameters can be different for each atom.
> Added new index on 'acoeff' of 'jastrowspin.py'

- examples/dask_h2o.py
- examples/parsl_h2o.py
- pyqmc/__init__.py
- pyqmc/dasktools.py
- pyqmc/dmc.py
- pyqmc/linemin.py
- pyqmc/parsltools.py
- pyqmc/slateruhf.py
- tests/test_dmc.py
When I was parallelizing DMC, I ran into a weird parsl bug, which motivated me to try using dask instead. This seems better so I think that should be preferred now. 
I also found a small bug in the line minimization code, which is fixed.
> DMC parallelization and dask integration

- pyqmc/linemin.py
- tests/test_line_minimization.py
> Line minimization 

- pyqmc/multislater.py
mo_coeff object in multislater should be taken from the PySCF CASCI object, not the Slater object.
> bug fix in multislater

- .travis.yml
- pyqmc/reblock.py
- tests/test_dmc.py
no more pyblock dependency in pyqmc
> remove pyblock 

- pyqmc/__init__.py
- pyqmc/dasktools.py
- pyqmc/reblock.py
default_jastrow now returns qwalk default 2body jastrow w/ cusp conditions
> default_jastrow update

- pyqmc/func3d.py
- tests/test_derivatives.py
Fixed a bug in Cutoffcusp where it was dividing by zero. Added test as well.
> CutoffCusp Bug

- pyqmc/jastrowspin.py
Some small changes are due to black formatting
> Added function to JastrowSpin to return components of U

- examples/cvmc_h2.py
- pyqmc/__init__.py
- pyqmc/cvmc.py
- pyqmc/dasktools.py
- pyqmc/obdm.py
Correlated sampling for cvmc, really rough, please give comments on cleaner implementation.
> Corr sampling

- examples/cvmc_h2.py
- pyqmc/cvmc.py
- pyqmc/linemin.py
- pyqmc/multislater.py
- pyqmc/obdm.py
- pyqmc/slateruhf.py
- tests/test_obdm.py
Fixed obdm for correlated sampling. Also added a new method to do line minimization, reduces code repetition.
Tests work well for h2, c and benzene cVMC. going to do a bit more testing on benzene and present on tuesday.
> Correlated sampling obdm fix

- pyqmc/slaterpbc.py
- pyqmc/testwf.py
- tests/test_derivatives.py
- tests/test_periodic.py
New PySCFSlaterPBC object for doing supercell calculation using primitive cell DFT. Derivatives pass tests, except for pgradient, which currently returns {}. Some testing files were updated to test the PBC object and fix bugs.
> Periodic slater object

- pyqmc/accumulators.py
- pyqmc/cvmc.py
Regularization for parameter gradients.
> Regularization

- pyqmc/dasktools.py
Distvmc hdf5 interface update, forgot to do it in the last pull req!
> Hdf5 distvmc

- pyqmc/tbdm.py
- tests/test_tbdm.py
Two-body density matrices implemented (without McMillan trick).
> Two-body density matrices

- pyqmc/dmc.py
- pyqmc/func3d.py
- pyqmc/slaterpbc.py
With these changes, periodic_he example runs dmc without errors.
1) take real part of the gradient for dmc moves
2) edit PolyPadeFunction.[gradient_]laplacian() to remove an unnecessary division by rvec, which might contain zeros and break dmc.
I also set the spin in get_supercell to remove warning and avoid wrong behavior for systems with nonzero spin.
> tested dmc

- pyqmc/accumulators.py
- pyqmc/cvmc.py
Small bugfix, forgot to regularize the second term in dpH = <E_L dpPsi> - <E_L><dpPsi>. Now it is included. 
Also rewrote some variables for clarity.
> Parameter gradient regularization bugfix

- doc/source/index.rst
- doc/source/optimize_orthogonal.rst
- examples/excited_state.py
- examples/excited_state_analyze.py
- pyqmc/dasktools.py
- pyqmc/linemin.py
- pyqmc/optimize_orthogonal.py
This function can optimize wave functions with a penalty on the overlap with any number of other wave functions.
> Add optimize_orthogonal

- pyqmc/jastrowspin.py
- pyqmc/multiplywf.py
Hi!
I made a generalized version of MultiplyWF class. The interface is consistent with the previous version, so there is no need to change other existing code. I did some manual testing and also tested it with he.py example; it is working. Please let me know if it breaks something else that I ignored. Thanks!
> Generalize MultiplyWF.

- pyqmc/__init__.py
- pyqmc/multislater.py
Added determinant tolerance for MultiSlater class. You can now map from PySCF to PyQMC with a determinant coefficient threshold.
> Tolerance for MultiSlater

- pyqmc/slaterpbc.py
- tests/test_twist.py
This pull request includes
1. bugfix for slaterpbc in the case of uneven occupation of kpoints
2. bugfix to mask the wrap as well as configs in orbital evaluation
3. some minor changes to slaterpbc
4. twist option in slaterpbc
5. test file for twisted boundary condition
> Twisted boundary conditions

- tests/test_dmc.py
should fix the variance bug in test_dmc
> change test_dmc jastrow cusp parameter from -1 to 1

- pyqmc/slater.py
wasn't properly checking if parameters are complex
> fix iscomplex checking in slater

- pyqmc/ewald.py
- pyqmc/multislater.py
- pyqmc/multislaterpbc.py
- pyqmc/obdm.py
- pyqmc/slater.py
> Remove lambda functions

- pyqmc/accumulators.py
- pyqmc/optimize_ortho.py
- pyqmc/slater.py
Fixes issue #182 and updates orthogonal optimization to work with complex wave functions.
> Ortho complex

- pyqmc/accumulators.py
- tests/integration/test_complex_linemin.py
Replaced expensive test with molecule, made mo coeffs complex.
Fixed a small bug in serialize_gradients, should not take real and imag parts of grads.
> Complex parameters test and bug fix

- pyqmc/ewald.py
Fixed a couple docstrings and a factor of 0.5 in e_single(). This missing factor only affects charged calculations.
> Small fixes in ewald.py

- pyqmc/mc.py
> save vmc acceptance to hdf

- pyqmc/optimize_ortho.py
There were a few places where I thought the optimize_orthogonal code could be made more compact, making functions easier to read through. I didn't change last function, optimize_orthogonal(), which is still pretty long.
The H2 example runs the same before and after these changes, and I verified along the way that each value is the same as the previous version.
> Condense some lines in optimize_orthogonal

- pyqmc/dmc.py
I've attached a demonstration of the problem.
[cumsum_errors.zip](https://github.com/WagnerGroup/pyqmc/files/5610847/cumsum_errors.zip)
> Dmc branching

- tests/unit/test_accumulators.py
Also checking whether travis deals with this better.
> updated test_accumulators to use gth-szv so that it's faster.

- .travis.yml
- pyqmc/__init__.py
- tests/unit/test_recover_pyscf.py
Also include a test for recover_pyscf.
> recover_pyscf now generates more sensible objects

- pyqmc/__init__.py
- pyqmc/multislater.py
- tests/integration/test_shci_wf.py
Fix a but in selecting determinants using HCI wave functions.
> Multislater bug

- pyqmc/__init__.py
> Added an option to only optimize the large MO coefficients in a given

- pyqmc/__init__.py
- pyqmc/recipes.py
Add kwarg `anchors` to OPTIMIZE; if None, it runs line minimization; otherwise, it's a list of hdf files to read in the anchor wfs, and the recipe runs orthogonal optimization with those anchors and `linemin_kws`
> Add optimize_orthogonal to OPTIMIZE recipe

- pyqmc/distance.py
- pyqmc/pbc.py
i noticed einsum is faster than dot. changed in distance.py and pbc.py
> change dot to einsum

- pyqmc/optimize_ortho.py
> add verbose kwarg to optimize_ortho

- pyqmc/orbitals.py
We found it's necessary to map coordinates back into the primitive cell for PySCF AO evaluation when the supercell is very large. This PR adds that in to PBCOrbitalEvaluatorKpoints.aos().
> map coordinates back into primitive cell in AO evaluation

- pyqmc/jastrowspin.py
Small changes to index labels for consistency
> Jastrow docs notation

- .github/workflows/python-package.yml
- examples/excited_state_h2.py
- pyqmc/linemin.py
- pyqmc/optimize_excited_states.py
- tests/integration/test_excited_state_sampler.py
Add a new function that can optimize N excited states simultaneously.
> New excited state optimization

- pyqmc/testwf.py
There wasn't a test that the saved intermediates returned by gradient_value actually work (it's tested for testvalue). So this adds a check when testing gradient_value to make sure the saved intermediates match
> Test saved_vals match from testvalue and gradient_value

- pyqmc/accumulators.py
- pyqmc/addwf.py
- pyqmc/determinant_tools.py
- pyqmc/distance.py
- pyqmc/dmc.py
- pyqmc/energy.py
- pyqmc/eval_ecp.py
- pyqmc/ewald.py
- pyqmc/func3d.py
- pyqmc/jastrowspin.py
- pyqmc/linemin.py
- pyqmc/mc.py
- pyqmc/multiplywf.py
- pyqmc/obdm.py
- pyqmc/optimize_excited_states.py
- pyqmc/optimize_ortho.py
- pyqmc/orbitals.py
- pyqmc/pbc.py
- pyqmc/reblock.py
- pyqmc/recipes.py
- pyqmc/slater.py
- pyqmc/tbdm.py
- pyqmc/testwf.py
- pyqmc/twists.py
Coded up all the grids listed in Mitas, Shirley, Ceperley JCP 1991 https://doi.org/10.1063/1.460849.
The code now precalculates the grids and stores them in a dictionary instead of generating them inside of get_rot.
> Add more ECP quadrature grids

- pyqmc/func3d.py
func3d value calls for the Jastrow are a noticeable chunk of time in profiling.
I rewrote the polynomial evaluations and found that value calls should individually be up to 10 faster in some cases, gradient_value and gradient_laplacian should be up to 20% faster.
> faster func3d polynomial evaluation

- pyqmc/recipes.py
Allows you to set rdm1=True when doing PBC calculations!
> Use k-points when doing periodic systems in recipes.

- pyqmc/dmc.py
- pyqmc/eval_ecp.py
This fixes a couple bugs in branching, tmoves, and drift limiting. Shouldn't change any real results, I would hope!
Note that this will break any previous DMC runs.
> Some fixes for ECP and dmc.

- pyqmc/testwf.py
- tests/unit/test_wf_derivatives.py
added test_testvalue_many function to testwf that tests whether running testvalue on all electrons individually is consistent with running testvalue_many with all electrons as the index.
> Test test value many

- pyqmc/three_body_jastrow.py
underscore needed backslash in text mode
> fix documentation latex error

- pyqmc/accumulators.py
- pyqmc/linemin.py
- pyqmc/stochastic_reconfiguration.py
- tests/integration/test_complex_linemin.py
- tests/integration/test_jastrow3.py
Added in accumulators for optimization, which include in them how to generate new parameter changes. 
This allows us to use other optimization strategies that may not need to compute the entire Sij matrix.
> Optimization accumulators

- doc/source/accumulators.rst
- pyqmc/ewald2d.py
- tests/unit/test_ewald.py
- Update source for accumulators doc
- Add return type hints
- Clarify variable subscripts in latex
- Small cleanup/typos
Ready to update online doc?
https://pyqmc.readthedocs.io/en/latest/accumulators.html
> Fix 2DEwald doc

- pyqmc/linemin.py
- pyqmc/stochastic_reconfiguration.py
- tests/integration/test_line_minimization.py
changed the epsilon default to something a bit more conservative.
> clean up the test, and add some more outputs for linemin.

- pyqmc/linemin.py
- pyqmc/stochastic_reconfiguration.py
- tests/integration/test_line_minimization.py
There was a sign error in the stochastic_reconfiguration moves. 
For some reason this passed our tests! Maybe we need more stringent optimization tests.
> Fix linemin

- pyqmc/coord.py
> Removed underscore when calling PeriodicConfigs._dist in coord.py

- pyqmc/orbitals.py
- pyqmc/pyscftools.py
- tests/conftest.py
- tests/unit/test_orbital_generator.py
the pyscf function `mf.to_uhf()` seems to require `mf` as an argument in some cases, and not accept an argument in others (depending on periodic or not). trying both seems to fix the issue.
> fix pyscf issue

- pyqmc/distance.py
This PR vectorized the distance.pairwise() function, making it much faster in small tests.
> Compute pairwise faster

- pyqmc/coord.py
- pyqmc/gps2.py
- pyqmc/wftools.py
- tests/unit/test_wf_derivatives.py
@nirvaank implemented a Gaussian process state two-body Jastrow a while back. I made some edits and updates and it's ready for some trials.
> Gps jastrow

- examples/excited_state_ensemble.py
- pyqmc/accumulators.py
- pyqmc/ensemble_optimization.py
- pyqmc/hdftools.py
- pyqmc/linemin.py
- pyqmc/stochastic_reconfiguration.py
Addresses #429 to get basic multi-updater support into the optimization routines.
> Batch optimization

- pyqmc/func3d.py
These are minor changes to PolyPadeFunction gradient-value and gradient-laplacian implementations, slightly simplifying and speeding up gradient-laplacian by about 20%, gradient-value by 2-3%.
I tested the evaluation speed on a coronene molecule and on CCO.
> speed up polypade implementation

- examples/excited_state_ensemble.py
- pyqmc/ensemble_optimization.py
- pyqmc/ensemble_optimization_wfbywf.py
- pyqmc/linemin.py
We optimize using $\Psi_i^2$ to evaluate energy and parameter gradients.
> Now we do ensemble optimization wf by wf

- pyqmc/jax/jastrowspin.py
Modified _parameterMap, pgradient, and _init_parameters to make the shape of acoeff compatible with pyqmc, while maintaining an augmented jnp array acoeff internally for JAX functions
> Make acoeff compatible with pyqmc
